In [1]:
# Data trapping

In [2]:
import pandas as pd                         #Data visualisation
df = pd.read_csv('titanic.csv')             #This case file is present in same folder
print(df.head())                         #head() function prints only 5 elements or rows

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [3]:
pd.options.display.max_columns=6
print(df.describe())                                            #use of describe function to determine statatical analysis

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


In [4]:
import numpy as np  #numpy for statatical analysis(bit more code requires than pandas)
data = df['age']
print(data)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64


In [5]:
print("mean=",np.mean(data))
print("median=",np.median(data))
print("50th percentile(median)=",np.percentile(data,50))
print("25th percentile(median)=",np.percentile(data,25))
print("75th percentile(median)=",np.percentile(data,75))
print("standard deviation=",np.std(data))
print("Variance=",np.var(data))

mean= 29.69911764705882
median= nan
50th percentile(median)= nan
25th percentile(median)= nan
75th percentile(median)= nan
standard deviation= 14.516321150817317
Variance= 210.7235797536662


C:\Users\RANSHER RAJ\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
C:\Users\RANSHER RAJ\Anaconda3\lib\site-packages\numpy\lib\function_base.py:3826: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)


In [6]:

small_df=df[['age','sex','survived']]                                #statatics using numpy using data from csv file
print(small_df.head())                                               
df2=small_df['age']                                                  # Generating subframes
data2=df2.head()
print(data2)


    age     sex  survived
0  22.0    male         0
1  38.0  female         1
2  26.0  female         1
3  35.0  female         1
4  35.0    male         0
0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64


In [7]:
print("mean=",np.mean(data2))                                            #statatics using numpy using data from csv file
print("median=",np.median(data2))
print("50th percentile(median)=",np.percentile(data2,50))
print("25th percentile(median)=",np.percentile(data2,25))
print("75th percentile(median)=",np.percentile(data2,75))
print("standard deviation=",np.std(data2))
print("Variance=",np.var(data2))

mean= 31.2
median= 35.0
50th percentile(median)= 35.0
25th percentile(median)= 26.0
75th percentile(median)= 35.0
standard deviation= 6.11228271597445
Variance= 37.36


In [8]:
                          #creating dartaframe column of true and false in sex column of df
df['male']=df['sex']=='male'
print(df)


     survived  pclass     sex  ...  alive  alone   male
0           0       3    male  ...     no  False   True
1           1       1  female  ...    yes  False  False
2           1       3  female  ...    yes   True  False
3           1       1  female  ...    yes  False  False
4           0       3    male  ...     no   True   True
..        ...     ...     ...  ...    ...    ...    ...
886         0       2    male  ...     no   True   True
887         1       1  female  ...    yes   True  False
888         0       3  female  ...     no  False  False
889         1       1    male  ...    yes   True   True
890         0       3    male  ...     no   True   True

[891 rows x 16 columns]


In [9]:
print(df['fare'].values)                              #printing all values of fare in array

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

In [10]:
print(df['fare'].head().values)                #printing only 5 fare using head()

[ 7.25   71.2833  7.925  53.1     8.05  ]


In [11]:
#converting dataframe to data (pandas dataframe to numpy array )
data = df[['pclass','fare','age']].head().values                   #If head() is removed, all data will be printed
print(data,'\n')


print('shape: ',data.shape,'\n')                               # actually data is array type hence shape will return dimension
print(type(data))

[[ 3.      7.25   22.    ]
 [ 1.     71.2833 38.    ]
 [ 3.      7.925  26.    ]
 [ 1.     53.1    35.    ]
 [ 3.      8.05   35.    ]] 

shape:  (5, 3) 

<class 'numpy.ndarray'>


In [12]:
print(data[0])                      #prints first row (index 0)
print(data[:,2])                     #prints 3rd column( index 2)
print(data[1,:])                     #print 2nd row (index 1)
print(data[1,1])                     #prints fixed element at index [1,1]

[ 3.    7.25 22.  ]
[22. 38. 26. 35. 35.]
[ 1.     71.2833 38.    ]
71.2833


In [13]:
mask=data[:,2]>=26                                   #masking: process of creating new array of data
print(mask,"\n\n")
print(data[mask],"\n\n")                            #both printing same
print(data[data[:,2]>=26],"\n\n")

print((data[:,2]>=26).sum())                        #for counting the data

[False  True  True  True  True] 


[[ 1.     71.2833 38.    ]
 [ 3.      7.925  26.    ]
 [ 1.     53.1    35.    ]
 [ 3.      8.05   35.    ]] 


[[ 1.     71.2833 38.    ]
 [ 3.      7.925  26.    ]
 [ 1.     53.1    35.    ]
 [ 3.      8.05   35.    ]] 


4


# Sactterplot

In [14]:
import matplotlib.pyplot as plt
plt.scatter(df['age'],df['fare'])
plt.xlabel('age')
plt.ylabel('fare')

Text(0, 0.5, 'fare')

In [15]:
type(df['fare'])

pandas.core.series.Series

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
X=df['survived'].head().values

In [18]:
print(X)

[0 1 1 1 0]


In [19]:
Y=df['male']=df['sex']=='male'                     #returning Boolean values
print(Y.head().values)

[ True False False False  True]


# Building Logistic Regression Model with sklearn 

In [20]:
from sklearn.linear_model import LogisticRegression
x=df[['fare','age']].head().values
y=df['survived'].head().values
model=LogisticRegression()
model.fit(x,y)
print(model.coef_,model.intercept_)           #as from result we have 0 = 0.26261656x + -0.09996329y + -0.00018963
                                              #from the linear equation ax+by+c = 0

[[ 0.26261656 -0.09996329]] [-0.00018963]


C:\Users\RANSHER RAJ\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [21]:
print(model.predict(x))
print(y[:5])

[0 1 0 1 0]
[0 1 1 1 0]
